
kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

outputs:
#   - name: 'print schema pdf'
#     type: pdf_sch_print
#     dir: docs
#     options:
#       output: '%f_schematic.%x'
      
      
#   - name: 'print schema svg'
#     type: svg_sch_print
#     dir: docs
#     options:
#       output: '%f_schematic.%x'

#   - name: 'print schema'
#     comment: "Print schematic (SVG)"
#     type: svg_sch_print
#     dir: docs
#     options:
#       output: '%p-Schematic_%r.%x'

  - name: 'print board'
    comment: "Print board (PDF)"
    type: pdf_pcb_print
    layers: 'user'
    dir: docs
    options:
      output: '%p-board_%r.%x'
