

kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

outputs:
  - name: 'print schema pdf'
    type: pdf_sch_print
    dir: docs
    options:
      output: '%f_schematic.%x'
      
      
  - name: 'print schema svg'
    type: svg_sch_print
    dir: docs
    options:
      output: '%f_schematic.%x'
